version: "3"
services:
  mysql:
    image: mysql:8.0.32
    container_name: agrix
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agrix
